name: CI

on:
    push:
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run Jest
              run: npm test

    type-check:
        name: Type check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Type check
              run: npx tsc --noEmit

    build-scan:
        name: Build and scan for leaked paths
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run debug build and capture logs
              run: |
                  set -o pipefail
                  DEBUG_FIREBASE_ADMIN=1 npm run build 2>&1 | tee build.log
            - name: Scan logs for absolute local paths
              run: |
                  # Look for common absolute path patterns on Unix and Windows
                  if grep -E "(/Users/|/home/|[A-Za-z]:\\\\)" build.log; then
                    echo "Error: absolute local path found in build output";
                    grep -nE "(/Users/|/home/|[A-Za-z]:\\\\)" build.log || true;
                    exit 1;
                  else
                    echo "No absolute local paths detected in build output";
                  fi
