name: Deploy Storybook

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: read
    pages: write
    id-token: write
    actions: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Build Storybook
              run: npm run build-storybook

            - name: Upload Storybook artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./storybook-static

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4

            - name: Show deployed Storybook URL
              if: success()
              run: |
                REPO=${{ github.repository }}
                OWNER=${{ github.repository_owner }}
                NAME=${REPO#*/}
                echo "Storybook deployed: https://${OWNER}.github.io/${NAME}"
