name: Deploy Storybook

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            retry_with_legacy_peer_deps:
                description: 'If true, install dependencies with --legacy-peer-deps (manual retry)'
                required: false
                default: 'false'
            retry_with_force:
                description: 'If true, install dependencies with --force (manual retry)'
                required: false
                default: 'false'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    pages: write
    id-token: write
    actions: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: |
                  if [ "${{ github.event.inputs.retry_with_force }}" = "true" ]; then
                    echo "Using npm install --force per workflow input"
                    npm install --force
                  elif [ "${{ github.event.inputs.retry_with_legacy_peer_deps }}" = "true" ]; then
                    echo "Using npm install --legacy-peer-deps per workflow input"
                    npm install --legacy-peer-deps
                  else
                    npm ci
                  fi

            - name: Build Storybook
              run: npm run build-storybook

            - name: Upload Storybook artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./storybook-static

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4

            - name: Show deployed Storybook URL
              if: success()
              run: |
                  REPO=${{ github.repository }}
                  OWNER=${{ github.repository_owner }}
                  NAME=${REPO#*/}
                  echo "Storybook deployed: https://${OWNER}.github.io/${NAME}"
