name: Playwright E2E

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            retry_with_legacy_peer_deps:
                description: 'If true, install dependencies with --legacy-peer-deps (manual retry)'
                required: false
                default: 'false'
            retry_with_force:
                description: 'If true, install dependencies with --force (manual retry)'
                required: false
                default: 'false'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: |
                  if [ "${{ github.event.inputs.retry_with_force }}" = "true" ]; then
                    npm install --force
                  elif [ "${{ github.event.inputs.retry_with_legacy_peer_deps }}" = "true" ]; then
                    npm install --legacy-peer-deps
                  else
                    npm ci
                  fi
            - name: Build
              run: npm run build
            - name: Install Playwright browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests (uses playwright.config.ts webServer)
              run: npx playwright test --reporter=github
